plugins {
    id 'com.android.application'
}

android {
    namespace 'app.invidious.webview'
    compileSdk 35

    defaultConfig {
        applicationId 'app.invidious.webview'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    // 纯框架 WebView，无需外部依赖
}
